server:
  port: 8888

spring:
    datasource:
        name: test
        url: jdbc:mysql://219.234.5.196:3306/mytest
        username: root
        password: yiyitong
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      static-path-pattern: /**
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cn.model


#FreeMarker 配置
spring.freemarker.allow-request-override: false
#Enable template caching.启用模板缓存
spring.freemarker.cache: false
spring.freemarker.check-template-location: true
spring.freemarker.charset: UTF-8
spring.freemarker.content-type: text/html
spring.freemarker.expose-request-attributes: false
spring.freemarker.expose-session-attributes: false
spring.freemarker.expose-spring-macro-helpers: false
#设置面板后缀
spring.freemarker.suffix: .ftl

#设置单个文件最大内存
multipart.maxFileSize: 50Mb
#设置所有文件最大内存
multipart.maxRequestSize: 50Mb
#自定义文件上传路径
web:
  upload-path: /root/IMG



#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql